import { Game } from './types';

export const PANTHERS_20252026_SCHEDULE: Game[] = [
    {
    id: 'p1',
    date: 'Sep 29, 2025',
    month: 'Sep',
    day: '29',
    opponent: 'vs Carolina Hurricanes',
    opponentLogo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Carolina_Hurricanes.svg/200px-Carolina_Hurricanes.svg.png',
    time: '6:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Preseason',
    gameNumber: 'PS 1',
    dateTimeISO: '2025-09-29T22:00:00Z',
    },
  {
    id: 'p2',
    date: 'Oct 04, 2025',
    month: 'Oct',
    day: '04',
    opponent: 'vs Tampa Bay Lightning',
    opponentLogo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Tampa_Bay_Lightning_Logo_2011.svg/200px-Tampa_Bay_Lightning_Logo_2011.svg.png',
    time: '7:00 PM ET',
    ticketStatus: 'Available',
    isPaid: false,
    type: 'Preseason',
    gameNumber: 'PS 2',
    dateTimeISO: '2025-10-04T23:00:00Z',
    },
  {
    id: 'espn-2026-02-26-0',
    date: 'Feb 26',
    month: 'Feb',
    day: '26',
    opponent: 'vs Toronto',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 1
  },
  {
    id: 'espn-2026-02-27-1',
    date: 'Feb 27',
    month: 'Feb',
    day: '27',
    opponent: 'vs Buffalo',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 2
  },
  {
    id: 'espn-2026-03-01-2',
    date: 'Mar 1',
    month: 'Mar',
    day: '1',
    opponent: 'at New York',
    time: '6:30 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 3
  },
  {
    id: 'espn-2026-03-03-3',
    date: 'Mar 3',
    month: 'Mar',
    day: '3',
    opponent: 'at New Jersey',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 4
  },
  {
    id: 'espn-2026-03-05-4',
    date: 'Mar 5',
    month: 'Mar',
    day: '5',
    opponent: 'at Columbus',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 5
  },
  {
    id: 'espn-2026-03-06-5',
    date: 'Mar 6',
    month: 'Mar',
    day: '6',
    opponent: 'at Detroit',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 6
  },
  {
    id: 'espn-2026-03-10-6',
    date: 'Mar 10',
    month: 'Mar',
    day: '10',
    opponent: 'vs Detroit',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 7
  },
  {
    id: 'espn-2026-03-12-7',
    date: 'Mar 12',
    month: 'Mar',
    day: '12',
    opponent: 'vs Columbus',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 8
  },
  {
    id: 'espn-2026-03-15-8',
    date: 'Mar 15',
    month: 'Mar',
    day: '15',
    opponent: 'at Seattle',
    time: '8:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 9
  },
  {
    id: 'espn-2026-03-17-9',
    date: 'Mar 17',
    month: 'Mar',
    day: '17',
    opponent: 'at Vancouver',
    time: '10:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 10
  },
  {
    id: 'espn-2026-03-19-10',
    date: 'Mar 19',
    month: 'Mar',
    day: '19',
    opponent: 'at Edmonton',
    time: '9:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 11
  },
  {
    id: 'espn-2026-03-20-11',
    date: 'Mar 20',
    month: 'Mar',
    day: '20',
    opponent: 'at Calgary',
    time: '9:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 12
  },
  {
    id: 'espn-2026-03-24-12',
    date: 'Mar 24',
    month: 'Mar',
    day: '24',
    opponent: 'vs Seattle',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 13
  },
  {
    id: 'espn-2026-03-26-13',
    date: 'Mar 26',
    month: 'Mar',
    day: '26',
    opponent: 'vs Minnesota',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 14
  },
  {
    id: 'espn-2026-03-28-14',
    date: 'Mar 28',
    month: 'Mar',
    day: '28',
    opponent: 'at New York',
    time: '1:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 15
  },
  {
    id: 'espn-2026-03-29-15',
    date: 'Mar 29',
    month: 'Mar',
    day: '29',
    opponent: 'at New York',
    time: '1:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 16
  },
  {
    id: 'espn-2026-03-31-16',
    date: 'Mar 31',
    month: 'Mar',
    day: '31',
    opponent: 'vs Ottawa',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 17
  },
  {
    id: 'espn-2026-04-02-17',
    date: 'Apr 2',
    month: 'Apr',
    day: '2',
    opponent: 'vs Boston',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 18
  },
  {
    id: 'espn-2026-04-04-18',
    date: 'Apr 4',
    month: 'Apr',
    day: '4',
    opponent: 'at Pittsburgh',
    time: '5:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 19
  },
  {
    id: 'espn-2026-04-05-19',
    date: 'Apr 5',
    month: 'Apr',
    day: '5',
    opponent: 'at Pittsburgh',
    time: '3:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 20
  },
  {
    id: 'espn-2026-04-07-20',
    date: 'Apr 7',
    month: 'Apr',
    day: '7',
    opponent: 'at Montreal',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 21
  },
  {
    id: 'espn-2026-04-09-21',
    date: 'Apr 9',
    month: 'Apr',
    day: '9',
    opponent: 'at Ottawa',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 22
  },
  {
    id: 'espn-2026-04-11-22',
    date: 'Apr 11',
    month: 'Apr',
    day: '11',
    opponent: 'at Toronto',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 23
  },
  {
    id: 'espn-2026-04-13-23',
    date: 'Apr 13',
    month: 'Apr',
    day: '13',
    opponent: 'vs New York',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 24
  },
  {
    id: 'espn-2026-04-15-24',
    date: 'Apr 15',
    month: 'Apr',
    day: '15',
    opponent: 'vs Detroit',
    time: '7:00 PM',
    ticketStatus: 'Pending',
    isPaid: false,
    type: 'Regular',
    gameNumber: 25
  },
];

export default PANTHERS_20252026_SCHEDULE;
